
spring:
  application:
    name: eureka-server #指定服务名称
  security:
    user:
      name: tt
      password: 123
eureka:
  instance:
    hostname: replica2 #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://zyz:123456@replica1:8002/eureka/
server:
  port: 8003